version: '3.7'

services:
  db:
    container_name: postgres-db
    image: 'postgres:14.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - OLIST_DB=olist
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data:/data
    ports:
      - "5432:5432"